name: optimizer-elo-ratings

on:
  schedule:
    - cron:  '59 * * * *'

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install git+https://github.com/microprediction/humpday
            pip install cmake
            pip install ultraopt
            pip install hyperopt
            pip install dlib 
            pip install py-bobyqa
            
      - name: update elo ratings and test
        run: |
          python update_optimizer_elo_ratings.py
   
      - name: create lb
        run: |
          python create_leaderboards.py
   
      - name: Show git status
        run: | 
          git status
          
      - name: Add regression_test_results files
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "my@email.com"
          git add --all           
      - name: Show git status
        run: | 
          git status
          
      - name: Commit
        run: |  
          git commit -a -m "commiting test results"
          
      - name: git pull I
        run: | 
          git pull
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
